// Fontes oficiais das normas. Para atualizar uma norma: salve a página do Planalto
// (ou o PDF do Cade) em data/raw/ e rode `npm run build:data`.
export const LAWS = [
  {
    id: 'lei-12529',
    sigla: 'Lei 12.529/2011',
    nome: 'Lei de Defesa da Concorrência',
    descricao: 'Estrutura o SBDC e dispõe sobre a prevenção e a repressão às infrações contra a ordem econômica.',
    arquivo: 'L12529.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12529.htm',
    status: 'revisada',
  },
  {
    id: 'cf',
    sigla: 'CF/1988',
    nome: 'Constituição Federal (recorte)',
    descricao: 'Arts. 1º a 3º, 5º (XXXII, LIV e LV), 37, 170 e 172 a 174 (o 171 foi revogado).',
    arquivo: 'constituicao.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
    status: 'beta',
    selecao: {
      1: true, 2: true, 3: true,
      5: ['inciso XXXII', 'inciso LIV', 'inciso LV'],
      37: true,
      170: true, 172: true, 173: true, 174: true, // art. 171 revogado pela EC 6/1995
    },
  },
  {
    id: 'lei-8137',
    sigla: 'Lei 8.137/1990',
    nome: 'Crimes contra a Ordem Econômica (recorte)',
    descricao: 'Arts. 4º e 7º: crimes contra a ordem econômica e as relações de consumo (os arts. 5º e 6º foram revogados pela Lei 12.529/2011).',
    arquivo: 'L8137.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/leis/l8137.htm',
    status: 'beta',
    selecao: { 4: true, 7: true },
  },
  {
    id: 'ricade',
    sigla: 'RICade',
    nome: 'Regimento Interno do Cade',
    descricao: 'Versão de 22/06/2026 publicada pelo Cade.',
    arquivo: 'RICade-2026-06-22.pdf',
    formato: 'pdf',
    fonte: 'https://www.gov.br/cade/pt-br/acesso-a-informacao/institucional/regimento-interno',
    status: 'beta',
  },
  {
    id: 'lacp',
    sigla: 'Lei 7.347/1985',
    nome: 'Lei da Ação Civil Pública',
    descricao: 'Texto compilado do Planalto.',
    arquivo: 'L7347Compilada.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/leis/l7347compilada.htm',
    status: 'beta',
  },
  {
    id: 'lindb',
    sigla: 'Decreto-Lei 4.657/1942',
    nome: 'Lei de Introdução às Normas do Direito Brasileiro (LINDB)',
    descricao: 'Inclui os arts. 20 a 30 (segurança jurídica nas decisões públicas).',
    arquivo: 'del4657compilado.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del4657compilado.htm',
    status: 'beta',
  },
  {
    id: 'cdc',
    sigla: 'Lei 8.078/1990',
    nome: 'Código de Defesa do Consumidor',
    descricao: 'Texto compilado do Planalto.',
    arquivo: 'L8078compilado.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm',
    status: 'beta',
  },
  {
    id: 'cpc',
    sigla: 'Lei 13.105/2015',
    nome: 'Código de Processo Civil',
    descricao: 'Texto compilado do Planalto.',
    arquivo: 'L13105.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm',
    status: 'beta',
  },
];
