// Fontes oficiais das normas. Para atualizar uma norma: salve a página do Planalto
// (ou o PDF do Cade) em data/raw/ e rode `npm run build:data`.
export const LAWS = [
  {
    id: 'lei-12529',
    sigla: 'Lei 12.529/2011',
    nome: 'Lei de Defesa da Concorrência',
    descricao: 'Estrutura o SBDC e dispõe sobre a prevenção e a repressão às infrações contra a ordem econômica.',
    arquivo: 'L12529.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12529.htm',
    status: 'revisada',
  },
  {
    id: 'ricade',
    sigla: 'RICade',
    nome: 'Regimento Interno do Cade',
    descricao: 'Versão de 22/06/2026 publicada pelo Cade.',
    arquivo: 'RICade-2026-06-22.pdf',
    formato: 'pdf',
    fonte: 'https://www.gov.br/cade/pt-br/acesso-a-informacao/institucional/regimento-interno',
    status: 'beta',
  },
  {
    id: 'lacp',
    sigla: 'Lei 7.347/1985',
    nome: 'Lei da Ação Civil Pública',
    descricao: 'Texto compilado do Planalto.',
    arquivo: 'L7347Compilada.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/leis/l7347compilada.htm',
    status: 'beta',
  },
  {
    id: 'cdc',
    sigla: 'Lei 8.078/1990',
    nome: 'Código de Defesa do Consumidor',
    descricao: 'Texto compilado do Planalto.',
    arquivo: 'L8078compilado.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm',
    status: 'beta',
  },
  {
    id: 'cpc',
    sigla: 'Lei 13.105/2015',
    nome: 'Código de Processo Civil',
    descricao: 'Texto compilado do Planalto.',
    arquivo: 'L13105.html',
    formato: 'html',
    fonte: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm',
    status: 'beta',
  },
];
